name: Build and Push to ECR

on:
  push:
    branches:
      - main

env:
  ECR_REGISTRY: 384005890259.dkr.ecr.eu-central-1.amazonaws.com
  ECR_REPOSITORY: counter-service-prod
  AWS_REGION: eu-central-1
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  BUILDKIT_INLINE_CACHE: 1
  BUILDKIT_SESSION_TIMEOUT: 90s

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Determine image tag
        id: determine-tag
        run: |
          echo "::set-output name=tag::$(date +'%Y%m%d')"

      - name: Build and tag Docker image
        id: build-image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:cs-prd${{ steps.determine-tag.outputs.tag }} .
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:cs-prd${{ steps.determine-tag.outputs.tag }}"

      - name: Push Docker image to Amazon ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.build-image.outputs.image }}
